name: Deploy Supabase Changes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: curl -fsSL https://deb.supabase.com/install.sh | sh

      - name: Deploy Database Changes
        run: supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhncHRvZ2tlY3h5cHdxbHNmdWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNzgwOTgsImV4cCI6MjA1NDg1NDA5OH0.qgjjaeyyoGYvxcIR8OCASptJvVXEcHbC2mjZYkhSifU
